// constants.js

const REMIT_PRIMARY = 622490000;
const REMIT_SECONDARY = 622490001;
const REMIT_TERTIARY = 622490002;
const DEFAULT_BATCH_SIZE = 50;
const DEFAULT_CONCURRENCY = 6;

module.exports = {
  REMIT_PRIMARY,
  REMIT_SECONDARY,
  REMIT_TERTIARY,
  DEFAULT_BATCH_SIZE,
  DEFAULT_CONCURRENCY,
};
